# GAS1NG@N, KA1TLYN ASHL3Y C.
#   2 ECE - C

# - - - 1st Problem on Manual - - - 

In [ ]:
# In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
# .std() calls.
# In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
# ndarray as X_normalized.npy

In [52]:
import numpy as np

# Step 1: Create a random 5x5 NumPy array
X = np.random.rand(5, 5)  # Generates values between 0 and 1
print("Original X:\n", X)

# Step 2: Calculate mean and standard deviation
mean = X.mean()
std = X.std() 
        
        #The code won't work without .std and .mean because 
        #standard deviation is not built-in 

print("\nMean of X:", mean)
print("Standard Deviation of X:", std)

# Step 3: Normalize the array using the formula Z = (X - mean) / std
X_normalized = (X - mean) / std
print("\nNormalized X:\n", X_normalized)

# Step 4: Save the normalized array to a file
np.save("X_normalized.npy", X_normalized)



Original X:
 [[0.50241385 0.928936   0.46392218 0.7726049  0.26729918]
 [0.26402077 0.7615834  0.81415909 0.3543524  0.14680447]
 [0.46631149 0.14026379 0.6509906  0.20716871 0.30065775]
 [0.39641506 0.5455631  0.42405565 0.82422931 0.0643856 ]
 [0.33451912 0.06903717 0.0968996  0.38676959 0.49288131]]

Mean of X: 0.42704976369125847
Standard Deviation of X: 0.24740612591927225

Normalized X:
 [[ 0.30461691  2.02859261  0.14903599  1.39671214 -0.6457018 ]
 [-0.65895294  1.35216391  1.56467153 -0.29383815 -1.13273385]
 [ 0.15869342 -1.15917087  0.90515476 -0.88874538 -0.51086859]
 [-0.12382355  0.47902345 -0.01210202  1.60537475 -1.46586574]
 [-0.37400303 -1.4470644  -1.33444618 -0.16280994  0.26608696]]
